### ISSUE TITLE
Reg - Android application Development

### ISSUE THREAD

**Issue by krishnaraj20** [dhilipsiva/feedback#1]
This is krishnaraj.V from salem tamilnadu.studying in Muthayammal Engineering College, i met you at inaguration of GEMS Club founded by Mr. Sakkaravarthi Ramanathan sir...i'm seeking for an resource for converting any website to android application with the permission of an website owner.. i hope you help me... provide me any resources sir!!

**Comment by dhilipsiva** [comment]
Hey @krishnaraj20. Apologies for the very late reply. I somehow missed this notification. Converting any website into App is very easy. Just create a WebView and set the url to whatever site you want to visit to.
