### ISSUE TITLE
Aspiring Web Developer 

### ISSUE THREAD

**Issue by saltgen** [dhilipsiva/feedback#2]
Hello @dhilipsiva, I am Sagnik. 

Recently I have applied for Appknox but guess due to insufficient experience I wasn't able to make it. Thanks for dropping me a response though.

I had a look at http://dhilipsiva.com/ and it has inspired me a lot as I'm building my own web portfolio now and I have a lot of pointers.  My request is if you could tell me about specific resources books/Internet which can help me gain pace and knowledge faster. I'm currently reading and going through the below resources for self-learning.

1. Coding for Entrepreneurs, Django Apps
2. React Tuts by Kirupa Chinnathambi
3. You Don't Know JS series, on Github

I too wanna be an all around Full Stack Developer, Web and Mobile.

Thanks,
Sagnik

**Comment by dhilipsiva** [comment]
Hi @saltgen, Nice to e-meet you.

Apologies on not being able to take the discussion further. Its just that we were looking for someone with more experience.

Yes - I have documented everything over here: [dhilipsiva/awesome-programmer](https://github.com/dhilipsiva/awesome-programmer).

Please feel free to Add / Update resources! 😄
