### ISSUE TITLE
Opensteer setup

### ISSUE THREAD

**Issue by jekoule** [dhilipsiva/feedback#3]
Hello @dhilipsiva, I am Jekoule and I would like to know how to setup Opensteer in amazon ec2. Do you have any guidance, tips who can help me figure out how to do it? any chance I can get one hour or two of consulting to help us make the right install? what could be the rate of these consultations hours?
Also, do you have any screenshot of the app, maybe a demo link or it looks just like https://www.newsteer.com/?

Thanks

**Comment by dhilipsiva** [comment]
Hello @jekoule ,

Apologies on the very late response. There is still a quite a lot of work pending for me to finish it. I don't find enough time to work on it. You are better off with newsteer for the time being.
